### PR TITLE
Added simple JSLint-compatible XML output formatter

### PR DESCRIPTION
**Pull request by vsviridov**

### CODE REVIEW

**Comment by brentlintner** [comment]
Just merging this in now. Appreciate the contribution. I added the --jslint-reporter option, but if anyone has a better option name I am up for suggestions. :-)

One thing I wanted to ask was I found this line:

https://github.com/vsviridov/node-jshint/blob/7734ddee0f1213b36e558d949d7b1d64bcb77bc1/lib/jslint_reporter.js#L32

It was truncating the file path, so a file wold be "b/hint.js" instead of "lib/hint.js" in the report. I removed it, but let me know if it is needed to be there. :-)

**Comment by vsviridov** [comment]
Oh, that was there to remove './' from the path. Jenkins' violations 
plugin is relly pissy about this for some reason. I guess there should 
be a better way of doing it. Maybe an option or a regex.

Cheers.

**Comment by brentlintner** [comment]
Ah crap. My bad then. Will throw in some regex asap. :-)

**Comment by brentlintner** [comment]
Ok cool, I think this should cover that. Let me know and ill push asap.

https://github.com/jshint/node-jshint/commit/4af71240beb479a0f567d36fc0922f6d1ee42fd3

**Comment by brentlintner** [comment]
Just pushed to npm. Apologies for the presumption Vasili.

Cheers,

**Comment by vsviridov** [comment]
I guess I just hacked it to fit my environment... So, it's all good... :)

**Pull request merged**
