### PR TITLE
Add/extra globals

### PR DESCRIPTION
**Pull request by rauchg**
Added a new option so that you can whitelist arbitrary globals from jshintrc

### CODE REVIEW

**Comment by brentlintner** [comment]
Thanks for the contribution. This looks good to me (in general), aside from some failing tests (but I need to fix others that are failing, so I can fix them myself if need be). I do have one nitpick question, though: Would you be open to calling the option `globals` instead of `extraglobals`? It feels slightly more succinct (at least, IMO), and I don't think that would cause conflicts. Additionally, it might also ensure a (relatively) easier upgrade path for the implementation of what is suggested in https://github.com/jshint/node-jshint/issues/104 (or just allow for the issue to be closed).

Thoughts?

**Comment by rauchg** [comment]
@brentlintner naming is up to you - tests were passing when I tried, maybe I forgot to include some commits. The reason I didn't go with `globals` is that maybe the implication there is that you override the other globals? Which is obviously not the case.

**Comment by brentlintner** [comment]
@guille Ah, OK. I can re-commit your commits with the option renamed to `globals` and merge into master, then (unless you want to do it, and be the committer). No worries about the tests (however odd)- I think it is a quick fix, anyways. I'll post when I've published, as well.

**Comment by rauchg** [comment]
Go ahead. Thanks for considering this @brentlintner

**Comment by brentlintner** [comment]
Sorry, this took a bit longer than I intended (work got in the way). Published all this as `v0.8.2`. If you are interested, check out [master](https://github.com/jshint/node-jshint/commits/master/) for your commits! :-)

Thanks again,

**Pull request closed without merging**
