### PR TITLE
Jshintignore merge defaults feature

### PR DESCRIPTION
**Pull request by johnmdonahue**
Cleaning up pull request [#75](https://github.com/jshint/node-jshint/pull/75). :-)

### CODE REVIEW

**Comment by brentlintner** [comment]
I pulled this in locally to test it out. Unexpectedly, I am getting a failing test?? (running Mac OS Lion btw).

See: https://gist.github.com/cbf29badad8e2f150754

I'm going to take a deeper look myself if I get the chance.

**Comment by brentlintner** [comment]
Also, if you wouldn't mind running and cleaning up any errors produced by `jake lint`, that would be great. :-)

**Comment by johnmdonahue** [comment]
Ha, yeah the test passes on my Mac, same OS. But it was an admittedly hacky test. It should at least sort the array before comparing. Also I didn't realize I needed to run through the linter. A silly thing to not assume in retrospect but once cleaned up, maybe it'd make sense to add the linter to the `test` task so that `jake test` by default hits the linter first. I'm happy to work on this but I'm headed out of town for the weekend and probably won't have much time to jump on it until early next week.

An additional thought: as I've been working on another project, it has become evident that a custom, non-merging `.jshintignore` might be a handy option - similar to how `options["--config"]` works currently. Thought on that?

For reference, if no one else jumps on it I'll take care of clearing the linter, fixing the array bug in my test and, if you agree, adding the linter to the `test` task and/or creating a non-merging `.jshintignore` flag (e.g. `options["--ignore"]`)

**Comment by brentlintner** [comment]
Haha, indeed! No worries, thanks for fixing that up and pushing the new commit. I can pull this in, unless you wanted to add anything else (let me know). :-)

I'm not so sure I (for one) like having `jake lint` run with `jake test` because they are separate tasks in general. If anything, I would have another task that does both, but running the linter is expected to be a commonly run task (just like testing), from my perspective.

A custom ignore option (like `--config`) would be cool IMO (in another pull request, is so?). (BTW, I wanted to also point you to this currently open [issue](https://github.com/jshint/node-jshint/issues/88), as the whole lookup process for `.jshintrc` (and possibly `.jshintignore`) files is being discussed).

Cheers!

**Comment by johnmdonahue** [comment]
Feel free to pull this in for this version if you want, however, the more I use this tool the more I fall in agreement with the model proposed in the issue you [referenced](https://github.com/jshint/node-jshint/issues/88#issuecomment-4582308).

Thanks.

**Comment by brentlintner** [comment]
Yeah, it sucks this and that issue both came about around the same time (argh!). I am glad he proposed a change, though, since I like it better as well (but didn't have time to really do it), vs going for consistent behaviour in the current version, which seemed practical at the time (and why I suggested that here..).

I hate to say (and not pull in you contribution which is greatly appreciated), but like you said, perhaps waiting for [that issue](https://github.com/jshint/node-jshint/issues/88#issuecomment-4582308) to be implemented and pulled in is best. :-s

**Comment by johnmdonahue** [comment]
No worries. I agree 100%.

@dominicbarnes are you working on this? Let me know if I can help out. RE: #88

**Comment by dominicbarnes** [comment]
@johnmdonahue I think I got this covered, check out my PR in case you have any other thoughts.

**Pull request closed without merging**
