### PR TITLE
Changing how node-jshint determines what config to use

### PR DESCRIPTION
**Pull request by dominicbarnes**
RE: #88

This change affects both `.jshintrc` and `.jshintignore` files. Now, starting with `cwd`, the script will search for a file with the name specified, and will traverse up one dir (`..`) until hitting the root.

For `.jshintrc` files, it will also check the `$HOME` directory before giving up.

Also, it should be noted that there is no longer a merge happening, it will stop with the first config file it finds.

### CODE REVIEW

**Comment by brentlintner** [comment]
W00t! I'll take an in depth look ASAP! Apologies for delaying (have been busy). :-(

Would you also mind squashing the 3 commits into one (since the logging/verbose diffs should not really be seen)?

Also, if you want to be super nice, and update the README (where it needs it), that would be brilliant, if not I don't mind at all doing so after merging this in.

Cheers,

**Comment by dominicbarnes** [comment]
Sadly, I don't think I'm well-versed enough in Git to start rebasing. (I think that's what you're asking, right?)

I can certainly update the README, I'll take care of that for sure.

**Comment by dominicbarnes** [comment]
On second thought, I went ahead and learned enough about rebase to combine those 3 commits. :)

I'm not sure how much you'll like my wording and other changes to the README, feel free to change it up.

**Comment by brentlintner** [comment]
Thanks for the rebase! Although, one of your [commits](https://github.com/dominicbarnes/node-jshint/commit/6c14fe97866d47058a05d11738ff11182178af90) (I believe) have some of the old messages still there (below the first line), and also don't mention that it changes how `.jshintignore` is looked up as well. Mind tweaking that (I don't mind doing that myself if not)? :-)

I also noticed there are some failing cli tests (?). And there is a lint error for an unused var (via `jake lint`).

Thanks for the README update as well (looks great!).

Aside from that, it looks good (to me). If you could clean up those few things I mentioned, I will publish this ASAP!

Cheers,

**Comment by dominicbarnes** [comment]
Howdy,

I'm going to be blocked out for most of this evening and weekend, so don't wait on me. If I get some time and notice you haven't already done it, I'll take care of it asap.

Thanks!

**Comment by brentlintner** [comment]
I got this. I plan to push and release today. :-)

**Comment by brentlintner** [comment]
Published 0.6.0. Everything seems solid. Let me know if you see/have an issues.

See the commit history here: https://github.com/jshint/node-jshint/commits/master/

Thanks again for the contribution!

**Comment by niftylettuce** [comment]
Awesome work.  Really awesome.

**Pull request closed without merging**
