### PR TITLE
Added jshint-eclipse to available editor integration

### PR DESCRIPTION
**Pull request by pulse00**

### CODE REVIEW

**Comment by brentlintner** [comment]
Awesome. Will merge this in, although it seems the absence of a newline after line 26 causes the MD to not be formatted correctly (in github). Mind adding that quickly? I can also do that as well, if not. Thanks!

**Comment by pulse00** [comment]
should be ok now.

**Comment by brentlintner** [comment]
Ok, cool. I just merged this to [master](https://github.com/jshint/node-jshint/commits/master/), although I noticed there was a `-` in that newline fix which was still causing a formatting issue, so (instead of going back and forth once more) I went ahead fixed it up myself (hope that is alright). :-) Thanks again! Closing.

**Comment by pulse00** [comment]
thanks a lot and sorry for the newline troubles ;)

**Comment by brentlintner** [comment]
No worries! :-)

**Pull request closed without merging**
