### PR TITLE
Allow files with .json extension

### PR DESCRIPTION
**Pull request by stefounet**
Allow files with .json extension to be collected and analyzed. 
Just modified a regex and tests.

### CODE REVIEW

**Comment by brentlintner** [comment]
Does JSHint support JSON (officially)? If this is so, I think this would be best as a CLI option because `json` is a subset of JavaScript and (I, for one) would not expect them to be picked up by default. I was thinking an option like `--with-json`, but perhaps a more ideal option would be a `--extra-ext` option that takes in a list of extensions to search for. Thoughts?

I also noticed there is JSONLint out there (and on NPM)... http://search.npmjs.org/#/jsonlint

**Comment by stefounet** [comment]
Yep, JSHint support JSON : from http://www.jshint.com/about/, "The
source can be JavaScript or JSON."
I don't think it needs an extra CLI option as most json files have the
.json ext. This should stay simple.
However, if you want me to add this option, i can do it.

Thanx for the jsonlint link, i will try it.

On 14 mars 2012, at 18:42, Brent Lintner
reply@reply.github.com
wrote:

**Comment by brentlintner** [comment]
Cool. I did not know that. :-)

I still think it should be it's own CLI option, because while it's supported, it's still a different type of file, and a user who does not want to check .json files (by default) should not have to use a CLI option to turn that off (IMO).

I reason I think (as an example) `--extra-ext .json` (or some other wording) is the best solution, is because it would allow the user to (ideally) specify multiple types of file extension(s) to run JSHint on, instead of adding a specific option like `--check-json` (or some other wording) that sticks around. FWIW, I figure `--extra-ext` could also take a comma delimited string (Ex: `--extra-ext .json,.html`).

**Comment by stefounet** [comment]
ok, let's go with --extra-ext !
i'll send a pull request asap

On Thu, Mar 15, 2012 at 4:56 PM, Brent Lintner <
reply@reply.github.com

**Comment by brentlintner** [comment]
That would be epic! (thanks!!)

PS, I wonder if there is a better option name than `--extra-ext`... hmmm.

**Comment by brentlintner** [comment]
PS, mind squashing the first commit into the second? If not, I can. Thanks!

**Comment by stefounet** [comment]
I tried to squash the two commits in my local repo but as i already 
pushed the first one to github, bam !
So I need to delete and recreate the github remote repo and then push my 
squashed commits

I'do it this evening !

Le 23/03/12 18:29, Brent Lintner a écrit :

> PS, mind squashing the first commit into the second? If not, I can. Thanks!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jshint/node-jshint/pull/91#issuecomment-4663948

## 

Stéphane RIOS - fasterize.com - 06 30 26 44 80

**Comment by brentlintner** [comment]
Can't you just `git push remote_name branch_name -f`? It might blow away our comments, but I am ok with that. Also welcome to just open another pull request and close this, instead. :-)

**Comment by brentlintner** [comment]
Closing since this was re-submitted with this pull request: https://github.com/jshint/node-jshint/pull/96

**Pull request closed without merging**
